kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64


steps:
# - name: build_and_test_image
#   image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
#   commands:
#   - apk add curl bash wget tar
#   - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
#   environment:
#     GEOIP_ACCOUNT_ID:
#       from_secret: geoip_account_id
#     GEOIP_LICENSE_KEY:
#       from_secret: geoip_license_key
#   when:
#     event:
#     - pull_request
#     - push
#     - tag

- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-nginx-proxy
    tags:
    - ${DRONE_COMMIT_SHA}
    - dev-${DRONE_BUILD_NUMBER}
    cache_from: quay.io/ukhomeofficedigital/dq-nginx-proxy:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
      exclude:
      - master
    event:
    - push

- name: trivy_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/trivyscanner:master
  commands:
  - trivy image --ignore-unfixed --exit-code 0 --no-progress quay.io/ukhomeofficedigital/dq-nginx-proxy:${DRONE_COMMIT_SHA}
  when:
    branch:
      exclude:
      - main
    event:
    - push

- name: build-master
  pull: if-not-exists
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-nginx-proxy
    tags:
    - latest
    - b${DRONE_BUILD_NUMBER}
    cache_from: quay.io/ukhomeofficedigital/dq-nginx-proxy:latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
